---
format: revealjs
title: Testing Your Own Functions with Pytest
title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```


![](../../../static/module7/m7_14.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
Now that we've learned how to move our functions to different files, it can be useful to move our test to different files as well. 

Let's take a look at how we can do this, looking at the `exponent_a_list` function.

Inside this one notebook `exponent`, we have written our test, but they're kind of out of place and not really relevant exactly for our analysis in this notebook.
:::

---

![](../../../static/module7/m7_15.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
We are going to put them in their own file that we can run and test independently before we did our analysis and just have our analysis code inside of our jupyter notebook.

We can do this by making a new python file by creating a text file.  
:::

---

![](../../../static/module7/m7_16.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
We can rename this file as `test_exponent_a_list.py`, ending the file with `.py`  to indicate that it's a python script. 
:::

---

![](../../../static/module7/m7_17.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
We can rename this file as `test_exponent_a_list.py`, ending the file with `.py`  to indicate that it's a python script.
:::

---

![](../../../static/module7/m7_18.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
Going back to the `exponents.ipynb` file, we cut these tests and paste them inside of the `test_exponent_a_list` python script.
:::

---

![](../../../static/module7/m7_20.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
For this to work, there's a few extra things we need to do.

It's important that you wrap these inside of a function, so we're going to call this function `test_exponent_a_list`.  

This does not need any function arguments because we just want the test function to execute the assert statement.
:::

---

![](../../../static/module7/m7_21.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
Finally, we need to add the import statement to tell python where the exponent a list function is coming from because it's not in this file. 

It's located in the `exponent_a_list` python script that we created earlier.

To import this function we write: 

```python
from exponent_a_list import exponent_a_list
```

We now have our tests saved inside of a function `test_exponent_a_list`, which is inside of a file named `test_exponent_a_list.py`. 

One thing to notice is both the function name and the file name begin with test. 

This is a nice trick that we use with our testing tool named `pytest` which automatically runs tests for us.
:::

---

![](../../../static/module7/m7_22.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
We must move to a terminal to run `pytest`. Scroll down and open “terminal”.  
:::

---

![](../../../static/module7/m7_23.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
To run `pytest`, we must be in the same directory where we have all of our test files stored.

It’s going to look for all the files that start with `test` and run all the functions inside of those files that start with `test`. 
:::

---

![](../../../static/module7/m7_24.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
We write `pytest` in the terminal, and this results in output that indicates to us if our tests pass.  

This looks like all our tests pass!
:::

---

![](../../../static/module7/m7_25.png){fig-align="center" width="95%" fig-alt="404 image"}


:::{.notes}
Let’s look at an example where our tests don’t pass. 

Errors could arise because of either an error in our test or in our function.  

Let’s return to the terminal and run the `pytest` command again. 

This time we get a lot more information. 

We got a very loud failure that something didn't go correctly.  

We get the output from the assert statement about which test failed. 

At this point, we would go back to either our function or test and try and fix the issue. 
:::


# Let’s apply what we learned!